name: Deep Learning for Anomaly Detection
description: Neural Question Answering
author: Cloudera Engineer
specification_version: 1.0
prototype_version: 1.0
date: "2020-09-29"
api_version: 1

environment_variables:
  AWS_ACCESS_KEY:
    default: "SUPER AWESOME AWS KEY"
    description: "Access Key ID for accessing S3 bucket"
    prompt_user: true

tasks:
  - type: create_job
    name: Install dependencies
    entity_label: install_deps
    script: install_deps.py
    arguments: None
    short_summary: Job to install dependencies and download training data.
    environment:
      TASK_TYPE: CREATE/RUN_JOB
    kernel: python3

  - type: run_job
    entity_label: install_deps
    short_summary: Running install dependencies training job.
    long_summary: >-
      Running the job to install dependencies.

  - type: start_application
    name: Application to serve NeuralQA UI
    subdomain: neuralqa
    script: app.py
    environment_variables:
      TASK_TYPE: START_APPLICATION
    kernel: python3
